version: '3.9'
services:
  db:
    image: postgres:16
    container_name: transoptima_db
    environment:
      POSTGRES_USER: transoptima
      POSTGRES_PASSWORD: transoptima
      POSTGRES_DB: transoptima
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
