services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=transoptima
      - POSTGRES_PASSWORD=transoptima
      - POSTGRES_DB=transoptima
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./web
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:
