version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: transoptima-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: transoptima
      POSTGRES_PASSWORD: transoptima
      POSTGRES_DB: transoptima
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
